### ISSUE TITLE
Cannot compile.

### ISSUE THREAD

**Issue by burnsjake** [mkazhdan/PoissonRecon#211]
Running Slackware64.
Git cloned the repo.
cd PoissonRecon
make -j10
...
Src/VertexFactory.inl: In member function ‘PlyProperty VertexFactory::PositionFactory<Real, Dim>::plyStaticReadProperty(unsigned int) const’:
Src/VertexFactory.inl:185:138: error: ‘idx’ is not a constant expression
  185 |                 return PlyProperty( _PlyNames[idx] , ToPlyType( _typeOnDisk ) , PLY::Type< Real >() , (int)offsetof( VertexType , coords[idx] ) );
      |                                                                                                                                          ^~~
Src/VertexFactory.inl: In member function ‘PlyProperty VertexFactory::PositionFactory<Real, Dim>::plyStaticWriteProperty(unsigned int) const’:
Src/VertexFactory.inl:191:138: error: ‘idx’ is not a constant expression
  191 |                 return PlyProperty( _PlyNames[idx] , ToPlyType( _typeOnDisk ) , PLY::Type< Real >() , (int)offsetof( VertexType , coords[idx] ) );
      |                                                                                                                                          ^~~
Src/VertexFactory.inl: In member function ‘PlyProperty VertexFactory::NormalFactory<Real, Dim>::plyStaticReadProperty(unsigned int) const’:
Src/VertexFactory.inl:221:138: error: ‘idx’ is not a constant expression
  221 |                 return PlyProperty( _PlyNames[idx] , ToPlyType( _typeOnDisk ) , PLY::Type< Real >() , (int)offsetof( VertexType , coords[idx] ) );
      |
...
 330 |                 return PlyProperty( _PlyNames[idx] , ToPlyType( _typeOnDisk ) , PLY::Type< Real >() , (int)offsetof( VertexType , coords[idx] ) );
      |                                                                                                                                          ^~~
make: *** [Makefile:186: Bin/Linux/SurfaceTrimmer.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:186: Bin/Linux/ChunkPLY.o] Error 1
make: *** [Makefile:186: Bin/Linux/EDTInHeat.o] Error 1
make: *** [Makefile:186: Bin/Linux/PointInterpolant.o] Error 1
make: *** [Makefile:186: Bin/Linux/AdaptiveTreeVisualization.o] Error 1
make: *** [Makefile:186: Bin/Linux/SSDRecon.o] Error 1
make: *** [Makefile:186: Bin/Linux/PoissonRecon.o] Error 1

Does the same with no -j appended. Just takes longer to get to the barf stage.

**Comment by mkazhdan** [comment]
I'm not 100% sure, though I would guess that it has to do with the use of the "offsetof" macro that doesn't translate nicely from C structs to C++ objects. It may be worthwhile to check how the macro is expanded by your compiler. For me it is:
        #define offsetof(s,m) ((::size_t)&reinterpret_cast<char const volatile&>((((s*)0)->m)))

**Comment by garrettseward** [comment]
I ran into this same error compiling on linux. I added:
```c++
#define offsetof2(s,m) ((::size_t)&reinterpret_cast<char const volatile&>((((s*)0)->m)))
```
to the top of `VertexFactory.inl` and changed all the `offsetof` references to `offsetof2`, and then I was able to compile. 

This is obviously not an ideal solution, but doing this enabled me to move past the compilation error for now.

**Comment by mkazhdan** [comment]
Thanks

**Comment by jewettaij** [comment]
This problem might be due to a change in the behavior of the g++ compiler.  I started running into this particular error when I upgraded GCC from 9.3.0 to 11.2.0 (as a result of upgrading from ubuntu 20.04 to ubuntu 21.10).

Anyway, using CLANG instead of GCC seems get around this particular error.  (But I can't confirm there aren't other issues with clang, because I run out of memory again when compiling the new version of this code.  The compilation memory requirements seem to have increased.  *That's a separate issue...*)
